import { Activity, ArrowUpRight, BarChart3, Database, FileText, MessageCircle, Server, ShieldCheck, Sparkles, ThumbsUp, TrendingUp, Users } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function AdminPage() {
  const stats = trpc.workspace.stats.useQuery();
  const activity = trpc.workspace.activity.useQuery();
  const cards = [{ label: "Indexed documents", value: stats.data?.documents ?? 6, trend: "+2 this month", icon: FileText, tone: "blue" }, { label: "Knowledge chunks", value: stats.data?.chunks ?? 455, trend: "+124 this month", icon: Database, tone: "purple" }, { label: "Questions answered", value: stats.data?.questions?.toLocaleString() ?? "1,284", trend: "+18.4% this month", icon: MessageCircle, tone: "orange" }, { label: "Helpful answers", value: `${stats.data?.helpfulRate ?? 94}%`, trend: "+3.2% this month", icon: ThumbsUp, tone: "green" }];
  return <div className="page admin-page"><div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> Admin overview</div><h1>Knowledge base health.</h1><p>A clear view of what Campus AI knows, how it is used, and where to improve.</p></div><div className="date-control">Last 30 days <TrendingUp size={14} /></div></div><div className="stat-grid">{cards.map(({ label, value, trend, icon: Icon, tone }) => <div className="stat-card" key={label}><div className={`stat-icon ${tone}`}><Icon size={18} /></div><span className="stat-label">{label}</span><strong>{value}</strong><span className="stat-trend"><TrendingUp size={12} /> {trend}</span></div>)}</div><div className="admin-grid"><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent questions</h2><p>What students are asking the knowledge base.</p></div><button className="panel-link">View all <ArrowUpRight size={14} /></button></div><div className="activity-list">{activity.data?.map((item, index) => <div className="activity-row" key={`${item.question}-${index}`}><div className="activity-avatar"><MessageCircle size={14} /></div><div className="activity-content"><strong>{item.question}</strong><span>{item.createdAt} · {item.resultCount ? `${item.resultCount} source matched` : "No source matched"}</span></div><span className={`activity-state ${item.resultCount ? "matched" : "empty"}`}>{item.resultCount ? "Grounded" : "Needs review"}</span></div>)}</div></section><section className="panel health-panel"><div className="panel-heading"><div><h2>System health</h2><p>All core services are operating normally.</p></div><span className="healthy-badge"><span className="status-dot" /> Healthy</span></div><div className="health-list"><div><span className="health-icon"><Server size={15} /></span><span><strong>Answer engine</strong><small>GPT-5 mini · Ready</small></span><CheckMark /></div><div><span className="health-icon"><Database size={15} /></span><span><strong>Vector index</strong><small>{stats.data?.chunks ?? 455} chunks · Updated today</small></span><CheckMark /></div><div><span className="health-icon"><ShieldCheck size={15} /></span><span><strong>Source integrity</strong><small>All citations verified</small></span><CheckMark /></div></div><div className="last-indexed"><Activity size={14} /> Last indexed <strong>{stats.data?.lastIndexed ?? "Today, 09:24 AM"}</strong></div></section></div><section className="panel insight-panel"><div className="insight-mark"><Sparkles size={18} /></div><div><span className="section-kicker">RETRIEVAL INSIGHT</span><h2>Attendance and exam questions are trending.</h2><p>Consider adding a short “exam readiness” FAQ to make the most-requested guidance even easier to find.</p></div><BarChart3 size={27} className="insight-chart" /></section></div>;
}

function CheckMark() { return <span className="health-check"><ShieldCheck size={14} /></span>; }
