import { useRef, useState } from "react";
import { Check, CloudUpload, FileText, MoreHorizontal, RefreshCw, Search, Trash2, UploadCloud } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function DocumentsPage() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState<string | undefined>();
  const inputRef = useRef<HTMLInputElement>(null);
  const documents = trpc.documents.list.useQuery({ query });
  return <div className="page documents-page"><div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> Admin workspace</div><h1>Document library</h1><p>Manage the official sources that power Campus AI answers.</p></div><button className="button-primary" onClick={() => inputRef.current?.click()}><UploadCloud size={16} /> Upload document</button></div><input ref={inputRef} type="file" accept=".pdf,.txt,.docx" hidden onChange={event => setSelected(event.target.files?.[0]?.name)} /><div className="upload-zone" onClick={() => inputRef.current?.click()}><div className="upload-icon"><CloudUpload size={22} /></div><div><strong>{selected || "Drop a document here, or browse"}</strong><span>PDF, DOCX, or TXT · up to 25 MB · indexing starts automatically</span></div><button onClick={event => { event.stopPropagation(); inputRef.current?.click(); }}>Choose file</button></div><div className="library-toolbar"><div className="library-title"><h2>Indexed sources <span>{documents.data?.length ?? 6}</span></h2><p>Latest document versions are preferred during retrieval.</p></div><div className="table-search"><Search size={15} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search documents" /></div></div><div className="document-table"><div className="table-head"><span>Document</span><span>Category</span><span>Chunks</span><span>Uploaded</span><span>Status</span><span /></div>{(documents.data || []).map(document => <div className="table-row" key={document.id}><div className="table-doc"><span className="doc-icon"><FileText size={16} /></span><div><strong>{document.documentName}</strong><span>Version {document.version} · {document.section}</span></div></div><span className="table-category">{document.category}</span><span className="table-muted">{document.chunks}</span><span className="table-muted">{document.uploaded}</span><span className="table-status"><span className="status-dot" /> {document.status}</span><button className="icon-button" aria-label={`Actions for ${document.documentName}`}><MoreHorizontal size={17} /></button></div>)}</div><div className="security-callout"><div className="callout-check"><Check size={15} /></div><div><strong>Source integrity is on</strong><p>Only indexed documents can influence answers. Every chunk retains its document name, section, and page where available.</p></div><RefreshCw size={17} className="callout-icon" /></div></div>;
}
