import { useState } from "react";
import { ArrowUpRight, BookOpen, FileText, Filter, Search, SlidersHorizontal } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function ExplorerPage() {
  const [query, setQuery] = useState("");
  const [submitted, setSubmitted] = useState("attendance");
  const [category, setCategory] = useState<string | undefined>();
  const categories = trpc.documents.categories.useQuery();
  const results = trpc.documents.search.useQuery({ query: submitted, category }, { enabled: submitted.length > 1 });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (query.trim().length > 1) setSubmitted(query.trim()); };
  return <div className="page explorer-page"><div className="page-heading-row"><div><div className="eyebrow"><span className="eyebrow-dot" /> Knowledge explorer</div><h1>Find the source behind the answer.</h1><p>Search across indexed campus documents and jump straight to the relevant passage.</p></div><div className="index-status"><span className="status-dot" /> 6 documents live</div></div><form className="explorer-search" onSubmit={submit}><Search size={19} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search policies, dates, requirements..." /><button type="submit">Search <ArrowUpRight size={15} /></button></form><div className="filter-bar"><div className="filter-label"><SlidersHorizontal size={15} /> Filter results</div><div className="category-pills">{(categories.data || ["All documents"]).map(item => <button key={item} className={category === item || (!category && item === "All documents") ? "active" : ""} onClick={() => setCategory(item === "All documents" ? undefined : item)}>{item}</button>)}</div><span className="result-count">{results.data?.length ?? 0} relevant results</span></div><div className="results-list">{results.isLoading ? <div className="loading-state">Searching indexed passages...</div> : results.data?.length ? results.data.map(result => <article className="result-card" key={result.id}><div className="result-card-top"><div className="result-document"><span className="doc-icon"><FileText size={16} /></span><div><strong>{result.documentName}</strong><span>{result.category} · Version {result.version}</span></div></div><span className="match-badge">{Math.round(result.score * 100)}% relevant</span></div><div className="result-section"><BookOpen size={14} /> {result.section} <span>•</span> Page {result.page}</div><p>{result.excerpt}</p><div className="result-footer"><span>Indexed {result.uploaded}</span><button>Open source <ArrowUpRight size={14} /></button></div></article>) : <div className="empty-search"><div className="empty-orb small"><Search size={20} /></div><h3>No reliable match found</h3><p>Try a different phrase or browse all documents. This assistant will not invent an answer when the source is missing.</p></div>}</div><div className="explorer-note"><Filter size={15} /><span>Search results show passages from the current campus knowledge base. Document versions are preserved so older policies are not silently discarded.</span></div></div>;
}
